paths:
  raw:
    raw_path: ''
    train_path: ''
    val_path: ''
    test_path: ''
  processed:
    raw_path: ''
    train_path: ''
    val_path: ''
    test_path: ''

transforms:
  - ToTensor: true
  - Resize: [256, 256]